# -*- coding: utf-8 -*-
"""英文→中文词元翻译：复合短语表（胸/背/腿核心动作）"""
COMPOUND_ZH: dict[str, str] = {
    "bench press": "卧推",
    "shoulder press": "肩推",
    "overhead press": "过头推举",
    "military press": "实力推举",
    "front raise": "前平举",
    "lateral raise": "侧平举",
    "rear delt raise": "反向飞鸟",
    "upright row": "直立划船",
    "bent over row": "俯身划船",
    "bent-over row": "俯身划船",
    "seated row": "坐姿划船",
    "concentration curl": "集中弯举",
    "preacher curl": "牧师凳弯举",
    "hammer curl": "锤式弯举",
    "biceps curl": "二头弯举",
    "triceps extension": "三头伸展",
    "tricep pushdown": "三头下压",
    "skull crusher": "颅骨粉碎",
    "pull-up": "引体向上",
    "pull up": "引体向上",
    "chin-up": "反手引体",
    "push-up": "俯卧撑",
    "sit-up": "仰卧起坐",
    "leg raise": "举腿",
    "leg curl": "腿弯举",
    "leg extension": "腿屈伸",
    "leg press": "腿举",
    "calf raise": "提踵",
    "hip thrust": "臀桥",
    "glute bridge": "臀桥",
    "hip extension": "髋伸",
    "hip adduction": "髋内收",
    "hip abduction": "髋外展",
    "good morning": "早安式",
    "front squat": "前蹲",
    "hack squat": "哈克深蹲",
    "split squat": "分腿蹲",
    "jump squat": "跳蹲",
    "step-up": "上台阶",
    "russian twist": "俄罗斯转体",
    "ab wheel": "健腹轮",
    "wheel rollout": "健腹轮推出",
    "kettlebell swing": "壶铃摆动",
    "muscle-up": "双力臂",
    "handstand push-up": "倒立俯卧撑",
    "mountain climber": "登山者",
    "jumping jack": "开合跳",
    "side plank": "侧平板",
    "dead bug": "死虫式",
    "donkey kick": "驴踢",
    "reverse fly": "反向飞鸟",
    "face pull": "面拉",
    "pallof press": "帕洛夫推",
    "landmine press": "地雷管推举",
    "turkish get-up": "土耳其起立",
    "zottman curl": "佐特曼弯举",
    "arnold press": "阿诺德推举",
    "cuban press": "古巴推举",
    "bradford press": "布拉德福德推举",
    "french press": "法国推举",
    "jm press": "JM推举",
    "tate press": "泰特推举",
    "w-press": "W型推举",
    "incline press": "上斜推举",
    "decline press": "下斜推举",
    "close-grip press": "窄距推举",
    "wide-grip press": "宽距推举",
    "reverse curl": "反握弯举",
    "wrist curl": "腕弯举",
    "reverse wrist curl": "反腕弯举",
    "hammer press": "锤式推举",
    "chest dip": "胸式臂屈伸",
    "triceps dip": "三头臂屈伸",
    "chest fly": "胸部飞鸟",
    "cable fly": "绳索飞鸟",
    "cable crossover": "绳索交叉夹胸",
    "pec deck": "蝴蝶机夹胸",
    "incline fly": "上斜飞鸟",
    "decline fly": "下斜飞鸟",
    "reverse crunch": "反向卷腹",
    "side bend": "体侧屈",
    "side crunch": "侧卷腹",
    "bicycle crunch": "自行车卷腹",
    "hanging knee raise": "悬垂举膝",
    "hanging leg raise": "悬垂举腿",
    "back extension": "背伸展",
    "hyperextension": "背屈伸",
    "pistol squat": "手枪蹲",
    "sissy squat": "西施蹲",
    "box jump": "跳箱",
    "broad jump": "立定跳远",
    "burpee": "波比跳",
    "rear delt row": "反向划船",
    "stiff leg deadlift": "直腿硬拉",
    "romanian deadlift": "罗马尼亚硬拉",
    "sumo deadlift": "相扑硬拉",
    "rack pull": "架上硬拉",
    "overhead squat": "过头深蹲",
    "goblet squat": "高脚杯深蹲",
    "bulgarian split squat": "保加利亚分腿蹲",
    "walking lunge": "行走箭步蹲",
    "rear lunge": "后撤箭步蹲",
    "lateral lunge": "侧向箭步蹲",
    "wall sit": "靠墙静蹲",
    "air squat": "徒手深蹲",
    "bodyweight squat": "徒手深蹲",
    "speed squat": "速度深蹲",
    "full squat": "全蹲",
    "deep squat": "深蹲",
    "narrow stance squat": "窄距深蹲",
    "wide squat": "宽距深蹲",
    "single leg squat": "单腿深蹲",
    "one leg squat": "单腿深蹲",
    "squat jump": "深蹲跳",
    "sled push": "雪橇推",
    "treadmill": "跑步机",
    "elliptical": "椭圆机",
    "rowing machine": "划船机",
    "air bike": "风阻单车",
    "battling ropes": "战绳",
    "battle ropes": "战绳",
    "medicine ball slam": "药球砸地",
    "wood chop": "劈柴",
    "jump rope": "跳绳",
    "renegade row": "叛徒划船",
    "single arm row": "单臂划船",
    "one arm row": "单臂划船",
    "one arm press": "单臂推举",
    "one arm snatch": "单臂抓举",
    "one arm curl": "单臂弯举",
    "alternate curl": "交替弯举",
    "alternating curl": "交替弯举",
    "cross body crunch": "交叉卷腹",
    "oblique crunch": "腹斜肌卷腹",
    "lying fly": "仰卧飞鸟",
    "standing fly": "站姿飞鸟",
    "shoulder internal rotation": "肩内旋",
    "shoulder external rotation": "肩外旋",
    "ankle circles": "踝绕环",
    "hip circles": "髋绕环",
    "knee circles": "膝绕环",
    "shoulder circles": "肩绕环",
    "hamstring stretch": "腘绳肌拉伸",
    "quad stretch": "股四头肌拉伸",
    "glute stretch": "臀肌拉伸",
    "calf stretch": "小腿拉伸",
    "hip flexor stretch": "髋屈肌拉伸",
    "piriformis stretch": "梨状肌拉伸",
    "chest stretch": "胸肌拉伸",
    "back stretch": "背部拉伸",
    "shoulder stretch": "肩部拉伸",
    "triceps stretch": "三头拉伸",
    "lat stretch": "背阔肌拉伸",
    "neck stretch": "颈部拉伸",
    "full body stretch": "全身拉伸",
    "spinal twist": "脊柱扭转",
    "seated spinal twist": "坐姿脊柱扭转",
    "lying spinal twist": "仰卧脊柱扭转",
    "chest opener": "扩胸",
    "shoulder opener": "开肩",
    "hip opener": "开髋",
    "groin stretch": "腹股沟拉伸",
    "one arm extension": "单臂伸展",
    "knee drive": "膝驱",
    "leg-hip raise": "举腿抬髋",
    # 修复重复/错误翻译
    "smith machine": "史密斯机",
    "cable rope": "绳索",
    "mixed grip": "混合握",
    "reverse grip": "反握",
    "close grip": "窄握",
    "wide grip": "宽握",
    "jm bench press": "JM卧推",
    "jm press": "JM推举",
    "prisoner sit-up": "囚徒仰卧起坐",
    "prisoner half sit-up": "囚徒半仰卧起坐",
    "half sit-up": "半仰卧起坐",
    "face press": "面部推举",
    "pronate-grip": "正握",
    "supinate-grip": "反握",
    "push press": "推举",
    "double push press": "双推举",
    "monster walk": "怪兽行走",
    "high knee against wall": "靠墙高抬腿",
    "drop push up": "递减俯卧撑",
    "weighted drop push up": "负重递减俯卧撑",
    "flexion leg sit up": "屈腿仰卧起坐",
    "straight arm": "直臂",
    "above head": "过头",
    "elbow dips": "肘撑臂屈伸",
    "posterior tibialis": "胫骨后肌",
    "tibialis": "胫骨前肌",
    "back pec stretch": "背部胸肌拉伸",
    "gironda sternum chin": "吉龙达胸骨引体",
    "sternum chin": "胸骨引体",
    "elevated seated row": "垫高坐姿划船",
    "palm rotational row": "掌心旋转划船",
    "rear drive": "后驱",
    "cable pull through": "绳索穿过式",
    "pull through": "穿过式",
    "behind neck press": "颈后推举",
    "behind neck": "颈后",
    # 补充低频动作
    "balance board": "平衡板",
    "body-up": "撑体上抬",
    "bottoms-up": "杯口朝上",
    "finger curls": "手指弯举",
    "kipping muscle up": "摆动双力臂",
    "muscle up": "双力臂",
    "single leg platform slide": "单腿平台滑动",
    "spell caster": "咒术师",
    "wind sprints": "疾风冲刺",
    "wrist rollerer": "腕卷绳",
    "butt-ups": "臀上抬",
    "clap push up": "击掌俯卧撑",
    "sphinx": "狮身人面式",
    "upward facing dog": "上犬式",
    "hug keens to chest": "抱膝贴胸",
    "inchworm": "尺蠖爬行",
    "butterfly yoga pose": "蝴蝶式",
    "sledge hammer": "大锤砸",
    "roller body saw": "健腹轮锯身",
    "left hook. boxing": "左勾拳",
    "split squats": "分腿蹲",
    "scissor jumps": "剪刀跳",
    "astride jumps": "跨跳",
    "star jump": "星形跳",
    "jack jump": "开合跳",
    "elevator": "电梯式",
    "handstand": "倒立",
    "flag": "旗式",
    "skin the cat": "翻猫式",
    "full maltese": "全马耳他式",
    "swimmer kicks": "打腿",
    "shoulder tap": "肩触地",
}
